const test=require('node:test'),assert=require('node:assert/strict'),D=require('./data.js'),M=require('./model.js'),OLD=D.records.slice(0,15),MapModel=require('./atlas-map.js');
test('所有样本年代、类型、来源和尺寸引用有效',()=>{assert.equal(M.validate(D),true);assert.equal(D.records.length,50);});
test('原15样本的119项字段和缺失记录完整保留',()=>{const a=M.aggregate(OLD);assert.equal(a.count,15);assert.equal(a.start,595);assert.equal(a.end,1855);assert.equal(a.filled,119);assert.equal(a.totalFields,120);assert.ok(Math.abs(a.completeness-119/120)<1e-12);assert.equal(a.typeCount,4);});
test('所有分类统计与交叉矩阵均守恒',()=>{for(const key of ['type','dynasty','region','material']){const a=M.aggregate(D.records);assert.equal(Object.values(a[key+'Counts']).reduce((s,v)=>s+v,0),50);}assert.equal(Object.values(M.aggregate(D.records).matrix).reduce((s,v)=>s+v,0),50);});
test('多条件筛选采用交集',()=>{const r=M.filter(D.records,{type:'桥梁',region:'华北',material:'石构'});assert.deepEqual(r.map(x=>x.id),['zhaozhou','lugou','seventeen','jadebelt']);assert.equal(M.filter(D.records,{type:'皇宫',dynasty:'明'}).length,9);});
test('区间筛选与建造范围求交，不丢弃跨边界样本',()=>{assert.deepEqual(M.filter(OLD,{start:600,end:600}).map(x=>x.id),['zhaozhou']);assert.deepEqual(M.filter(OLD,{start:1706,end:1706}).map(x=>x.id),['luding']);});
test('未载明材料与已确认砖木体系分开，缺失不作为0',()=>{assert.deepEqual(M.filter(OLD,{material:'未载明'}).map(x=>x.id),['zhili']);assert.deepEqual(M.filter(OLD,{material:'砖木复合'}).map(x=>x.id),['qiao']);const r=D.records.find(x=>x.id==='chengzhi');assert.equal(M.fieldFlags(r)[5],true);assert.equal(M.fieldFlags(r)[6],true);});
test('空结果完整度和年代为空，避免误报100%',()=>{const a=M.aggregate(M.filter(D.records,{search:'不存在的建筑'}));assert.equal(a.count,0);assert.equal(a.completeness,null);assert.equal(a.start,null);assert.equal(a.end,null);});
test('搜索可以命中建筑名称、原址或成就关键词',()=>{assert.equal(M.filter(D.records,{search:'河北'}).length,2);assert.deepEqual(M.filter(D.records,{search:'减柱'}).map(x=>x.id),['baohe']);});
test('全部15件都有带来源和限定关系的尺寸，共41项尺寸24项计数',()=>{assert.ok(OLD.every(r=>r.sizes.length>0));assert.equal(OLD.reduce((n,r)=>n+r.sizes.length,0),41);assert.equal(OLD.reduce((n,r)=>n+r.counts.length,0),24);assert.equal(D.sources.slice(0,28).length,28);});
test('近似值、下限和局部尺寸保持语义',()=>{const z=D.records.find(r=>r.id==='zhili');assert.equal(z.sizes[0].relation,'approx');assert.equal(z.sizes[2].relation,'gt');const c=D.records.find(r=>r.id==='chengzhi');assert.equal(c.sizes[0].relation,'gt');const y=D.records.find(r=>r.id==='yinyu');assert.equal(y.sizes[0].value,125.97);assert.equal(y.sizes[0].unit,'cm');assert.ok(y.sizes[0].scope.includes('局部门洞'));assert.ok(y.dataGaps.some(g=>g.field==='全宅面积'));});
test('计数与字段来源丢失会被拒绝',()=>{const a=structuredClone(D);a.records[0].counts[0].sourceId='missing';assert.throws(()=>M.validate(a));const b=structuredClone(D);b.records[0].provenance.date.sourceIds=['missing'];assert.throws(()=>M.validate(b));const c=structuredClone(D);c.records.find(r=>r.id==='zhili').provenance.material.sourceIds=['zhili-size'];assert.throws(()=>M.validate(c));});
test('浏览器数据与可编辑JSON保持完全一致',()=>{const fs=require('node:fs');assert.deepEqual(D,JSON.parse(fs.readFileSync(require('node:path').join(__dirname,'data/architectures.json'),'utf8')));});

test('扩充固定50座，统计为374/400且不掩盖空尺寸',()=>{const a=M.aggregate(D.records);assert.equal(a.count,50);assert.equal(a.end,1909);assert.equal(a.filled,374);assert.equal(a.totalFields,400);assert.deepEqual(a.typeCounts,{桥梁:14,官府:6,皇宫:14,民居:16});assert.equal(D.sources.length,75);assert.equal(D.records.reduce((s,r)=>s+r.sizes.length+r.counts.length,0),111);assert.ok(D.records.some(r=>r.sizes.length===0));});
test('所有新增建筑书内容完整，诗篇均为四行独立内容',()=>{const added=D.records.slice(15);assert.equal(added.length,35);assert.ok(added.every(r=>r.reading.history&&r.reading.story.length===2&&r.reading.poem.length===4&&r.reading.photoCaption));assert.equal(new Set(added.map(r=>r.reading.poem.join(''))).size,35);});
test('聚合不遗漏或重复样本，七个地域有独立分组',()=>{const groups=MapModel.groupRecords(D.records,D.regions);const ids=groups.flatMap(g=>g.records.map(r=>r.id));assert.equal(ids.length,50);assert.equal(new Set(ids).size,50);assert.ok(groups.length<50);assert.ok(groups.every(g=>g.records.every(r=>r.region===g.region)));assert.equal(D.regions.length,7);});
test('缩放仅改变可视窗口，筛选结果不被覆盖',()=>{const all=M.filter(D.records,{}),groups=MapModel.groupRecords(all,D.regions,1360,1440);assert.equal(all.length,50);assert.ok(groups.every(g=>g.records.every(r=>r.date.start<=1440&&r.date.end>=1360)));assert.ok(groups.some(g=>g.records.filter(r=>r.date.start===1420).length>=3));});
test('50条图版记录具有有效本地资产或明确的原创示意',()=>{const fs=require('node:fs'),path=require('node:path'),credits=JSON.parse(fs.readFileSync(path.join(__dirname,'data/photo-credits.json'),'utf8'));assert.equal(Object.keys(credits).length,50);for(const r of D.records){const p=credits[r.id];assert.ok(p);if(p.kind==='illustration'){assert.equal(r.id,'huaian');continue;}assert.ok(p.author&&p.license&&p.page);assert.ok(fs.existsSync(path.join(__dirname,p.local)));}});
