import fs from 'node:fs/promises';
import path from 'node:path';
import net from 'node:net';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const root=path.dirname(fileURLToPath(import.meta.url)),qa=path.join(root,'qa');await fs.mkdir(qa,{recursive:true});
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function freePort(){return await new Promise((resolve,reject)=>{const s=net.createServer();s.on('error',reject);s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p));});});}
const servicePort=await freePort(),debugPort=await freePort();
const server=spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,PORT:String(servicePort)},windowsHide:true,stdio:'ignore'});
const browser=spawn('C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--disable-extensions','--remote-allow-origins=*',`--remote-debugging-port=${debugPort}`,`--user-data-dir=${path.join(qa,'browser-profile')}`,'about:blank'],{windowsHide:true,stdio:'ignore'});
let ws;const runtimeErrors=[],checks=[];
async function until(fn,label){const deadline=Date.now()+20000;let error;while(Date.now()<deadline){try{const r=await fn();if(r)return r;}catch(e){error=e;}await delay(100);}throw Error('等待超时：'+label+(error?' / '+error.message:''));}
try{
  await until(async()=>{const r=await fetch(`http://127.0.0.1:${servicePort}/`,{signal:AbortSignal.timeout(800)});return r.ok;},'预览服务');
  await until(async()=>{const r=await fetch(`http://127.0.0.1:${debugPort}/json/version`,{signal:AbortSignal.timeout(800)});return r.ok;},'独立Edge');
  const target=await(await fetch(`http://127.0.0.1:${debugPort}/json/new?about:blank`,{method:'PUT'})).json();ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.addEventListener('open',resolve,{once:true});ws.addEventListener('error',reject,{once:true});});
  let id=0;const pending=new Map();ws.addEventListener('message',event=>{const m=JSON.parse(event.data);if(m.id){const p=pending.get(m.id);if(p){pending.delete(m.id);m.error?p.reject(Error(m.error.message)):p.resolve(m.result);}}else if(m.method==='Runtime.exceptionThrown')runtimeErrors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text);});
  const send=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}));});
  const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;};
  async function click(selector,count=1){const point=await evaluate(`(()=>{const el=document.querySelector(${JSON.stringify(selector)});if(!el)throw Error('Missing '+${JSON.stringify(selector)});el.scrollIntoView({behavior:'instant',block:'center'});const r=el.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`);await send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:count,...point});await send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:count,...point});}
  async function check(name,expression){assert.ok(await evaluate(expression),name);checks.push(name);if(!/可从主图|照片或原创|营造故事|四行原创|图版章保留/.test(name))console.log('PASS',name);}
  async function screenshot(name,full=false,keepTooltip=false){await evaluate(`document.querySelector('#toast').classList.remove('visible');${keepTooltip?'':"document.querySelector('#chart-tooltip').hidden=true"}`);await delay(400);const options={format:'png',captureBeyondViewport:full};if(full){const m=await send('Page.getLayoutMetrics');options.clip={x:0,y:0,width:m.cssContentSize.width,height:m.cssContentSize.height,scale:1};}const r=await send('Page.captureScreenshot',options);await fs.writeFile(path.join(qa,name),Buffer.from(r.data,'base64'));}
  async function hover(selector){const point=await evaluate(`(()=>{const el=document.querySelector(${JSON.stringify(selector)});el.scrollIntoView({behavior:'instant',block:'center'});const r=el.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`);await send('Input.dispatchMouseEvent',{type:'mouseMoved',...point});await delay(60);}
  async function svgPoint(selector,x,y,press=false){const point=await evaluate(`(()=>{const el=document.querySelector(${JSON.stringify(selector)});el.scrollIntoView({behavior:'instant',block:'center'});const p=new DOMPoint(${x},${y}).matrixTransform(el.getScreenCTM());return {x:p.x,y:p.y}})()`);await send('Input.dispatchMouseEvent',{type:'mouseMoved',...point});await delay(60);if(press){await send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...point});await send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...point});}}



  await send('Page.enable');await send('Runtime.enable');await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await send('Emulation.setDeviceMetricsOverride',{width:1920,height:1080,deviceScaleFactor:1,mobile:false});
  await send('Page.navigate',{url:`http://127.0.0.1:${servicePort}/`});await until(()=>evaluate(`document.readyState==='complete'&&!!window.AtlasBook&&AtlasData.records.length===50`),'50座图谱');
  await check('固定50座、50本书、75条来源且没有已删除的专题',`AtlasApp.records().length===50&&Object.keys(AtlasBookContent).length===50&&Object.keys(AtlasPhotos).length===50&&document.querySelectorAll('.source-entry').length===75&&!document.querySelector('iframe')`);
  await check('聚合覆盖全部50座且类型小图总数守恒',`[...AtlasMap.groups.values()].reduce((n,g)=>n+g.records.length,0)===50&&document.querySelectorAll('#atlas-chart .node').length<50&&[...document.querySelectorAll('.mini-type-chart button')].reduce((n,b)=>n+Number(b.textContent),0)===50&&document.querySelector('.years strong').textContent==='595—1909'`);
  const noOverflow=`document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight`;
  const centered=`(()=>{const a=document.querySelector('.atlas-space').getBoundingClientRect();return Math.abs(a.left+a.width/2-innerWidth/2)<3})()`;
  const labelsClear=`(()=>{const boxes=[...document.querySelectorAll('#atlas-chart .node-label')].map(el=>el.getBBox());return boxes.every((a,i)=>boxes.every((b,j)=>i===j||a.x+a.width<=b.x||b.x+b.width<=a.x||a.y+a.height<=b.y||b.y+b.height<=a.y))})()`;

  const allNamed=`[...document.querySelectorAll('#atlas-chart .node')].every(node=>node.querySelectorAll('.node-label').length===1)`;
  await check('总览中每个可见点位均有名称',allNamed);
  for(const type of ['民居','官府','皇宫','桥梁']){
    await click('#type-filters [data-type="'+type+'"]');
    await check(type+'分类中每个点位统一显示名称',allNamed+'&&'+labelsClear);
    await screenshot('统一名称_'+type+'.png');await click('#reset-filters');
  }
  await click('#labels-toggle');await check('名称开关统一隐藏全部标签',`document.querySelectorAll('#atlas-chart .node-label').length===0`);await click('#labels-toggle');await check('名称开关统一恢复全部标签',allNamed);
  const beforeSelection=await evaluate(`[...document.querySelectorAll('#atlas-chart .node-label')].map(el=>el.textContent)`);
  await evaluate(`AtlasApp.select('kunning')`);await check('选择建筑不会改变聚合名称格式',`JSON.stringify([...document.querySelectorAll('#atlas-chart .node-label')].map(el=>el.textContent))===${JSON.stringify(JSON.stringify(beforeSelection))}`);await evaluate(`AtlasApp.select('zhaozhou')`);
  await check('首页主图居中、标签不遮挡、无溢出',noOverflow+'&&'+centered+'&&'+labelsClear);await screenshot('50座时空图谱.png');await screenshot('统一名称_全部建筑.png');
  const clusterKey=await evaluate(`[...AtlasMap.groups].find(([,g])=>g.records.length>=8)[0]`);await hover(`[data-cluster="${clusterKey}"] .node-hit`);await check('聚合点悬停显示成员与展开提示',`!document.querySelector('#chart-tooltip').hidden&&document.querySelector('#chart-tooltip').textContent.includes('近邻建筑')`);await click(`[data-cluster="${clusterKey}"] .node-hit`);await check('单击聚合点展开名录',`!document.querySelector('#cluster-list').hidden&&document.querySelectorAll('[data-cluster-book]').length>=8`);await screenshot('50座聚合名录.png');const member=await evaluate(`document.querySelector('[data-cluster-book]').dataset.clusterBook`);await click('[data-cluster-book]');await check('名录成员打开正确建筑书',`document.querySelector('#book-dialog').open&&AtlasBook.record.id===${JSON.stringify(member)}`);await click('#book-close');await delay(30);
  await click('#atlas-zoom-in');await check('年代放大保持样本筛选不变，窗口可移动',`AtlasMap.view.end-AtlasMap.view.start===680&&AtlasApp.records().length===50&&!document.querySelector('#atlas-window').disabled`);await evaluate(`document.querySelector('#atlas-window').value='1700';document.querySelector('#atlas-window').dispatchEvent(new Event('input',{bubbles:true}))`);await check('年代窗口移动并保持标签清晰',`AtlasMap.view.start>1000&&`+labelsClear);await screenshot('50座年代放大.png');await evaluate(`AtlasMap.view.start=550;AtlasMap.view.end=700;document.querySelector('#search').value='怀远';document.querySelector('#search').dispatchEvent(new Event('input',{bubbles:true}))`);await check('搜索会自动显示视窗之外的命中建筑',`!!document.querySelector('#atlas-chart [data-record="huaiyuan"]')&&AtlasApp.records().length===1`);await click('#reset-filters');await click('#atlas-zoom-reset');await check('全览恢复50座聚合',`AtlasMap.view.start===550&&AtlasMap.view.end===1910&&[...AtlasMap.groups.values()].reduce((n,g)=>n+g.records.length,0)===50`);
  for(const id of await evaluate('AtlasData.records.map(r=>r.id)')){
    const location=await evaluate(`(()=>{const node=document.querySelector('#atlas-chart [data-record="${id}"]');return node?{single:true}:{single:false,key:[...AtlasMap.groups].find(([,g])=>g.records.some(r=>r.id===${JSON.stringify(id)}))[0]}})()`);
    if(location.single)await click(`#atlas-chart [data-record="${id}"] .node-hit`);else{await click(`[data-cluster="${location.key}"] .node-hit`);await click(`[data-cluster-book="${id}"]`);}
    await check(id+'可从主图独立打开历史、图版与正确书名',`AtlasBook.record.id===${JSON.stringify(id)}&&AtlasBook.page===0&&document.querySelector('#book-title').textContent===AtlasData.records.find(r=>r.id===${JSON.stringify(id)}).name`);
    await until(()=>evaluate(`[...document.querySelectorAll('#book-spread img')].every(i=>i.complete&&i.naturalWidth>0)`),'图版'+id);
    await check(id+'照片或原创示意均可正常读取',`AtlasPhotos[${JSON.stringify(id)}].kind==='illustration'?!!document.querySelector('.concept-stage svg'):document.querySelector('.book-photo img').naturalWidth>0`);
    await click('#book-next');await check(id+'营造故事、模型和来源可用',`AtlasBook.page===1&&!!document.querySelector('.book-art .art-building')&&document.querySelectorAll('.book-evidence a').length>0`);
    await click('#book-next');await check(id+'四行原创题咏完整',`AtlasBook.page===2&&document.querySelectorAll('.book-poem p').length===4&&document.querySelector('.book-original').textContent.includes('原创')`);
    await click('[data-book-chapter="3"]');await check(id+'图版章保留数据档案入口',`AtlasBook.page===3&&!!document.querySelector('#book-dossier')`);await click('#book-close');await delay(20);
  }
  await evaluate(`AtlasApp.select('hegui');AtlasBook.open('hegui');AtlasBook.go(1)`);await screenshot('50座方楼建筑书.png');await click('#book-close');await evaluate(`AtlasApp.select('chengqi');AtlasBook.open('chengqi');AtlasBook.go(1)`);await screenshot('50座圆楼建筑书.png');await click('#book-close');
  await click('.mini-type-chart [data-type="民居"]');await check('新增民居联动正确',`AtlasApp.records().length===16&&document.querySelector('.overview-number strong').textContent==='16件'`);await click('#reset-filters');
  await evaluate(`document.querySelector('#search').value='淮安';document.querySelector('#search').dispatchEvent(new Event('input',{bubbles:true}))`);await click('#atlas-chart [data-record="huaian"] .node-hit');await check('授权未核实的照片明确替换为原创示意',`document.querySelector('.concept-photo').textContent.includes('非实景摄影')&&!document.querySelector('.concept-photo img')`);await click('#book-close');await click('#reset-filters');
  await evaluate(`document.querySelector('#search').value='不存在';document.querySelector('#search').dispatchEvent(new Event('input',{bubbles:true}))`);await check('空结果没有虚构数据',`AtlasApp.records().length===0&&!document.querySelector('#empty-state').hidden&&document.querySelector('.years strong').textContent==='—'`);await click('#empty-reset');
  await click('#analysis-open');await click('[data-analysis="structure"]');await evaluate('new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))');await check('结构与材料矩阵覆盖新增土楼、铁桥、廊桥',`document.querySelectorAll('.matrix-cell').length===72&&document.querySelector('[data-matrix="围合土楼|土木复合"]')&&document.querySelector('[data-matrix="铁桁梁桥|铁构"]')`);await screenshot('50座结构分析.png');await click('[data-matrix="围合土楼|土木复合"]');await check('土楼交叉筛选联动5座',`AtlasApp.records().length===5`);await click('#analysis-dialog [data-close]');await click('#reset-filters');
  await click('#analysis-open');await click('[data-analysis="time"]');await evaluate('new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))');await check('50个时间轴点位独立避让',`(()=>{const nodes=[...document.querySelectorAll('#timeline-chart .timeline-hit')].map(el=>({x:Number(el.getAttribute('cx')),y:Number(el.getAttribute('cy'))}));return nodes.length===50&&nodes.every((a,i)=>nodes.every((b,j)=>i===j||Math.hypot(a.x-b.x,a.y-b.y)>11))})()`);await click('#analysis-dialog [data-close]');
  await send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:qa});const csvName='筑迹_建筑样本_50件.csv';await fs.rm(path.join(qa,csvName),{force:true});await click('#csv-export');await until(async()=>{try{return (await fs.readFile(path.join(qa,csvName),'utf8')).endsWith('"');}catch{return false;}},'导出50座');const csv=await fs.readFile(path.join(qa,csvName),'utf8');assert.equal(csv.split('\r\n').length,51);assert.ok(csv.includes('> 3,000')&&csv.includes('125.97cm')&&csv.includes('中山桥'));checks.push('50座完整CSV和旧尺寸限定关系正确导出');
  for(const [width,height]of [[1440,900],[1366,768]]){await send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:false});await delay(100);await check(width+'主图居中且无横向溢出',`document.documentElement.scrollWidth<=innerWidth&&`+centered+'&&'+labelsClear);await screenshot('50座图谱'+width+'.png');}
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await send('Page.reload',{ignoreCache:true});await until(()=>evaluate(`document.readyState==='complete'&&!!window.AtlasBook`),'手机50座');await check('手机首页无横向溢出，图谱自身可滑动',`document.documentElement.scrollWidth<=innerWidth&&document.querySelector('.atlas-stage').scrollWidth>document.querySelector('.atlas-stage').clientWidth`);await screenshot('50座图谱手机.png',true);
  await evaluate(`document.querySelector('#search').value='怀远';document.querySelector('#search').dispatchEvent(new Event('input',{bubbles:true}))`);await click('#atlas-chart [data-record="huaiyuan"] .node-hit');await check('手机建筑书正常打开且无横向溢出',`document.querySelector('#book-dialog').open&&document.querySelector('#book-dialog').scrollWidth<=document.querySelector('#book-dialog').clientWidth`);await screenshot('50座手机建筑书.png');await click('#book-close');
  await send('Page.navigate',{url:new URL('./index.html',import.meta.url).href});await until(()=>evaluate(`document.readyState==='complete'&&!!window.AtlasBook&&AtlasData.records.length===50`),'离线50座');await evaluate(`AtlasApp.select('seventeen');AtlasBook.open('seventeen')`);await until(()=>evaluate(`document.querySelector('.book-photo img').complete&&document.querySelector('.book-photo img').naturalWidth>0`),'离线新增照片');await check('50座图谱与新增照片完全离线可用',`location.protocol==='file:'&&AtlasApp.records().length===50&&AtlasBook.record.id==='seventeen'`);
  assert.equal(runtimeErrors.length,0,runtimeErrors.join('\n'));checks.push('无未处理的浏览器异常');await fs.writeFile(path.join(qa,'verification.json'),JSON.stringify({passed:true,checks,runtimeErrors},null,2));console.log('完成：'+checks.length+'项检查通过。');await send('Browser.close');
}finally{ws?.close();browser.kill();server.kill();}
